### PR TITLE
fix: Change the position of the footer to fixed and add a bottom valu…

### PR DESCRIPTION
**Pull request by Erick559**
Changed the position value to fixed and also added a bottom value of 0 to ensure the footer is always in the view port.

### CODE REVIEW

**Comment by madina0801** [comment]
Hi, thank you for your efforts~ We need to see it only when we scrolled down to the end of the content~ Cause now on Home page it's seen even when we didn't scroll to the bottom. Will you do it?

**Comment by Erick559** [comment]
okay no problem at all.

**Comment by Erick559** [comment]
I refactored it once more hope that was the final look you are going for.

**Comment by madina0801** [comment]
Can you add the "main" class to About component? So it will look like this:
```
function About () {
  return (
      <div className="main">
        <h2>About</h2>
        <p>JobTrackr is created to keep track of your job applications. Made with love. &#x1F497;</p>
      </div>
  );
};
export default About;
```

**Comment by Erick559** [comment]
okay i get what you are trying to achieve. My apologies I didn't look at the about page to notice that the footer wasn't at the bottom. Let me come up with a solution asap.

**Comment by Erick559** [comment]
Hi I think i was able to fix the issue. The footer is now at the bottom of the page and once you start adding content to the point it starts scrolling it will still remain at the bottom. I just added a classname to the app component which allowed me to style it adding flexbox then auto margined the footer to the bottom of the screen.

**Comment by madina0801** [comment]
Looks good! Thank you~

**Comment by Erick559** [comment]
You're welcome🫡

**Pull request merged**
